version: "3.1"
services:
  # mongodb://iweb:strongpassword@localhost:27017
  mongodb:
    image: "mongo:6.0.2"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: iweb
      MONGO_INITDB_ROOT_PASSWORD: strongpassword
      MONGO_INITDB_DATABASE: # TODO
    ports:
      - "27017:27017"

  # http://localhost:8000
  a2reservasrest:
    build: .
    environment:
      mongo_url: "mongodb://iweb:strongpassword@mongodb:27017"
      mongo_database: # TODO
      mongo_collection: # TODO
    ports:
      - "8000:8000"
